default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: james
  password:

development:
  <<: *default
  database: bulletproof_development

test:
  <<: *default
  database: bulletproof_test

production:
  <<: *default
  database: bulletproof_production
